# Generated by Django 5.1.1 on 2024-10-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_of_publication']},
        ),
    ]
