# Generated by Django 5.1.2 on 2024-10-23 17:15

import car.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[car.validators.YearValidator()]),
        ),
    ]
